name: Basic Manual Workflow

on:
  workflow_dispatch:

jobs:
  echo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Echo a message
        run: echo "This is a manually triggered workflow!"
